---
- name: DEVNET Test Playbook
  hosts: localhost
  gather_facts: false

  vars:
    test_org_id: "{{ lookup('env','MERAKI_ORG_ID') }}" # Set this to your test organization ID
    test_product: "wireless"  # Change this to the product you want to test
    test_network_type: "production"  # Change this to the network type you want to test [production, test]
    test_upgrade_time: "{{ '%Y-%m-%dT03:00:00' | strftime((now(fmt='%s') | int) + 2419200) }}"  # 28 days from now (within Meraki "at most 1 month" limit)
    freshdesk_api_key: "{{ lookup('env', 'FRESHDESK_API_KEY') }}"
    freshdesk_domain: "{{ lookup('env', 'FRESHDESK_DOMAIN') }}" # Set this to your Freshdesk domain via env variable
    pi_interfaces:
      pi4:
        wired: 10.20.100.91
        wireless: 10.20.200.240
      pi5:
        wired: 10.20.100.94
        wireless: 10.20.200.142
    iperf3_tests:
      - name: wired_to_wired
        client_bind: "{{ pi_interfaces.pi4.wired }}"
        server_bind: "{{ pi_interfaces.pi5.wired }}"
      - name: wired_to_wireless
        client_bind: "{{ pi_interfaces.pi4.wired }}"
        server_bind: "{{ pi_interfaces.pi5.wireless }}"
      - name: wireless_to_wireless
        client_bind: "{{ pi_interfaces.pi4.wireless }}"
        server_bind: "{{ pi_interfaces.pi5.wireless }}"

  tasks:
    - name: Load version policies from file
      ansible.builtin.include_vars:
        file: version_policies.yml
        name: version_policies

    # - name: Return identity of current API user
    #   cisco.meraki.administered_identities_me_info:
    #   register: current_user

    # - name: Gather Meraki Organizations
    #   cisco.meraki.organizations_info:
    #   register: org_response

    # - name: Store just the list of organizations
    #   ansible.builtin.set_fact:
    #     organizations: "{{ org_response.meraki_response }}"

    - name: Get networks in the organization
      cisco.meraki.networks_info:
        organizationId: "{{ test_org_id }}"
      register: org_networks

    - name: Set networkId fact for testing
      # This is just for testing purposes, to avoid looping through all networks
      ansible.builtin.set_fact:
        test_network_id: "{{ org_networks.meraki_response[1].id }}"

    - name: Get firmware versions for each network
      cisco.meraki.networks_firmware_upgrades_info:
        networkId: "{{ item.id }}"
      loop: "{{ org_networks.meraki_response }}"
      register: org_network_firmware_versions

    - name: Build dictionary of firmware versions by network
      ansible.builtin.set_fact:
        firmware_by_network: >-
          {{ dict(
               org_network_firmware_versions.results
                 | map(attribute='item.id')
                 | zip(
                     org_network_firmware_versions.results
                       | map(attribute='meraki_response')
                   )
             ) }}

    - name: Get network firmware versions
      cisco.meraki.networks_firmware_upgrades_info:
        networkId: "{{ test_network_id }}"
      register: network_firmware_versions

    - name: Store available upgrades in a list where version is > current and releaseType matches the test policy
      # Use version_compare to select versions > the current version and >= releaseType in version_policies
      ansible.builtin.set_fact:
        available_upgrades: >-
          {{ firmware_by_network[test_network_id].products[test_product].availableVersions
             | selectattr('releaseType', 'in', ['beta', 'candidate', 'stable']
                if version_policies[test_product][test_network_type] == 'beta'
                else (['candidate', 'stable']
                  if version_policies[test_product][test_network_type] == 'candidate'
                else ['stable']
                )
             )
             | selectattr('shortName', 'version_compare', firmware_by_network[test_network_id].products[test_product].currentVersion.shortName, '>')
             | list }}

    - name: Schedule firmware upgrade for test_network_id
      cisco.meraki.networks_firmware_upgrades:
        networkId: "{{ test_network_id }}"
        products: >-
          {{
            dict([
              (test_product, {
                'nextUpgrade': {
                  'time': test_upgrade_time,
                  'toVersion': {
                    'id': available_upgrades[0].id
                  }
                }
              })
            ])
          }}
      when: available_upgrades | length > 0

    - name: Pause the playbook and wait for user confirmation
      ansible.builtin.pause:
        prompt: "Press Enter to continue after confirming the firmware upgrade in the Meraki Dashboard."

    - name: Download Meraki Community RSS feed
      ansible.builtin.get_url:
        url: "https://community.meraki.com/yuzje69629/rss/board?board.id=firmwareupgrades"
        dest: "/tmp/meraki_firmwareupgrades.xml"
        mode: '0644'

    - name: Parse RSS item descriptions
      community.general.xml:
        path: "/tmp/meraki_firmwareupgrades.xml"
        xpath: "//item/description"
        content: text
      register: rss_descriptions

    - name: Parse RSS item links
      community.general.xml:
        path: "/tmp/meraki_firmwareupgrades.xml"
        xpath: "//item/link"
        content: text
      register: rss_links

    - name: Extract description strings from matches
      ansible.builtin.set_fact:
        rss_description_strings: "{{ rss_descriptions.matches | map(attribute='description') | list }}"

    - name: Extract link strings from matches
      ansible.builtin.set_fact:
        rss_link_strings: "{{ rss_links.matches | map(attribute='link') | list }}"

    - name: Zip descriptions and links into a dictionary
      ansible.builtin.set_fact:
        rss_items_dict: "{{ dict(rss_description_strings | zip(rss_link_strings)) }}"

    - name: Find matching RSS link in rss_items_dict
      ansible.builtin.set_fact:
        matching_rss_link: >-
          {{
            (rss_items_dict | dict2items
              | selectattr('key', 'search', available_upgrades[0].shortName | regex_escape)
              | list
              | first
            ).value
            if (
              rss_items_dict | dict2items
              | selectattr('key', 'search', available_upgrades[0].shortName | regex_escape)
              | list
              | length > 0
            )
            else ''
          }}

    - name: Debug matching RSS link
      ansible.builtin.debug:
        msg: "Matching RSS Link: {{ matching_rss_link }}"

    - name: Create Freshdesk Ticket
      ansible.builtin.uri:
        url: "https://{{ freshdesk_domain }}/api/v2/tickets"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Basic {{ freshdesk_api_key | b64encode }}"
        body_format: json
        body:
          description: >
            A new firmware upgrade has been scheduled for testing in the organization {{ test_org_id }}.<br><br>

            The upgrade is set for {{ test_upgrade_time }}.<br><br>

            {{ available_upgrades[0].shortName }} changelog: {{ matching_rss_link }}
          subject: "New Firmware Upgrade Scheduled For Testing"
          email: "jose.valdez@meraki.net"  # Replace with your email address
          priority: 3  # 1: Low, 2: Normal, 3: High, 4: Urgent
          status: 2      # 2: Open, 3: Pending, 4: Resolved, 5: Closed
        status_code: 201
      register: freshdesk_ticket

    - name: Pause the playbook and wait for user confirmation
      ansible.builtin.pause:
        prompt: "Press Enter to continue after confirming the firmware upgrade ticket has been created."

    - name: Include iperf3 testing tasks
      ansible.builtin.include_tasks: iperf3_testing.yml

    - name: Add iperf3 results as a reply to the Freshdesk Ticket
      ansible.builtin.uri:
        url: "https://{{ freshdesk_domain }}/api/v2/tickets/{{ freshdesk_ticket.json.id }}/reply"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Basic {{ freshdesk_api_key | b64encode }}"
        body_format: json
        body:
          body: >
            Pre-Upgrade iperf3 test results:<br><br>

            Wired to Wired: from {{ iperf3_tests[0].client_bind }} to {{ iperf3_tests[0].server_bind }}<br><br>

            Sent summary: {{ iperf3_wired_to_wired_output.end.sum_sent }}<br><br>

            Received summary: {{ iperf3_wired_to_wired_output.end.sum_received }}
        status_code: 201
      when: iperf3_wired_to_wired_output is defined

    - name: Pause the playbook and wait for user confirmation
      ansible.builtin.pause:
        prompt: "Press Enter to continue after confirming the iperf results were posted to the ticket."

    - name: Cancel firmware upgrade for test_network_id
      cisco.meraki.networks_firmware_upgrades:
        networkId: "{{ test_network_id }}"
        products: >-
          {{
            dict([
              (test_product, {
                'nextUpgrade': {
                  'time': test_upgrade_time,
                  'toVersion': {
                    'id': network_firmware_versions.meraki_response.products[test_product].currentVersion.id
                  }
                }
              })
            ])
          }}
      when: available_upgrades | length > 0
